//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNorthWind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling_Orders
    {
        public int IdSellingOrder { get; set; }
        public int IdEmployee { get; set; }
        public int IdProduct { get; set; }
        public int Quantity { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }

        public Employees IdEmployeeNavigation { get; set; }
        public Products IdProductsNavigation { get; set; }
    }
}
